//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public Nullable<int> Ip_id { get; set; }
        public Nullable<int> File_path_id { get; set; }
        public Nullable<int> result { get; set; }
        public string requestType { get; set; }
        public string requestTime { get; set; }
    
        public virtual File File { get; set; }
        public virtual IP IP { get; set; }
    }
}
